### ISSUE TITLE
audit fails to build with linux-5.17 headers

### ISSUE THREAD

**Issue by trofi** [linux-audit/audit-userspace#252]
Noticed build failure when tried to update linux-headers from `5.16` to `5.17` in downstream distribution.

Both current git checkout and older releases fail for me as:

```
audit> swig -o audit_wrap.c -python -I. -I../../.. -I../../../lib -I/<<NIX>>/python3-3.9.11/include/python3.9 ./../src/auditswig.i
audit> /<<NIX>>/bash-5.1-p16/bin/bash ../../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../..  -I. -I../../.. -I../../../lib -I/<<NIX>>/python3-3.9.11/include/python3.9  -shared -g -O2 -c -o _audit_la-audit_wrap.lo `test -f 'audit_wrap.c' || echo './'`audit_wrap.c
audit> libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../.. -I. -I../../.. -I../../../lib -I/<<NIX>>/python3-3.9.11/include/python3.9 -g -O2 -c audit_wrap.c  -fPIC -DPIC -o .libs/_audit_la-audit_wrap.o
audit> audit_wrap.c: In function '_wrap_audit_rule_data_buf_set':
audit> audit_wrap.c:5010:17: error: cast specifies array type
audit>  5010 |     arg1->buf = (char [])(char *)memcpy(malloc((size)*sizeof(char)), (const char *)(arg2), sizeof(char)*(size));
audit>       |                 ^
audit> audit_wrap.c:5010:15: error: invalid use of flexible array member
audit>  5010 |     arg1->buf = (char [])(char *)memcpy(malloc((size)*sizeof(char)), (const char *)(arg2), sizeof(char)*(size));
audit>       |               ^
```

I suspect it's a side-effect of https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ed98ea2128b6fd83bce13716edf8f5fe6c47f574 change:

```diff
@@ -514,1 +514,1 @@ struct audit_rule_data {
-	char		buf[0];	/* string fields buffer */
+	char		buf[];	/* string fields buffer */
```

**Comment by Blarse** [comment]
Hi, I had the same problem yesterday after updating headers to 5.17.

I found the original thread [here](https://www.spinics.net/lists/fedora-devel/msg297998.html) and a workaround [here](https://src.fedoraproject.org/rpms/audit/blob/rawhide/f/audit-3.0.8-flex-array-workaround.patch)

**Comment by trofi** [comment]
Proposed change as https://github.com/linux-audit/audit-userspace/pull/253

**Comment by stevegrubb** [comment]
This is a duplicate of issue/236. This was also discussed on the mail list. The preferred solution is to rewrite the bindings so that SWIG is not used at all. Each distribution can work around this in their own way. I have given patches out to demonstrate how Fedora is working around the issue. But we have to leave SWIG behind because it makes buggy code. We can also use this to reduce the libaudit python API. The function that is failing to build looks like it was never used because the code is completely wrong.

**Comment by trofi** [comment]
Let's close as a duplicate of #236 then.

I must say it's very confusing to keep upstream broken and suggest using distribution-specific patches just to have the package building.

**Comment by stevegrubb** [comment]
I agree. I wished the effect of removing the zero length array patch was known in advance so that this whole problem could have been avoided.
