### ISSUE TITLE
build failure: databuf_test

### ISSUE THREAD

**Issue by LordGrimmauld** [linux-audit/audit-userspace#474]
While packaging the new `4.1.0` update for nixpkgs, i ran into the following issue:

```
Making all in test
make[4]: Entering directory '/home/grimmauld/coding/audit-userspace/auparse/test'
depbase=`echo lookup_test.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I../..  -I../../auparse -I../../lib   -g -O2 -MT lookup_test.o -MD -MP -MF $depbase.Tpo -c -o lookup_test.o lookup_test.c &&\
mv -f $depbase.Tpo $depbase.Po
/nix/store/00zrahbb32nzawrmv9sjxn36h7qk9vrs-bash-5.2p37/bin/bash ../../libtool  --tag=CC   --mode=link gcc  -g -O2 -static  -o auparselol_test auparselol_test.o ../../auparse/libauparse.la ../../lib/libaudit.la ../../common/libaucommon.la
/nix/store/00zrahbb32nzawrmv9sjxn36h7qk9vrs-bash-5.2p37/bin/bash ../../libtool  --tag=CC   --mode=link gcc  -g -O2 -static  -o auparse_test auparse_test.o ../../auparse/libauparse.la ../../lib/libaudit.la ../../common/libaucommon.la
/nix/store/00zrahbb32nzawrmv9sjxn36h7qk9vrs-bash-5.2p37/bin/bash ../../libtool  --tag=CC   --mode=link gcc  -g -O2 -static  -o databuf_test databuf_test.o ../../auparse/libauparse.la ../../lib/libaudit.la ../../common/libaucommon.la
libtool: link: gcc -g -O2 -o databuf_test databuf_test.o  ../../auparse/.libs/libauparse.so /home/grimmauld/coding/audit-userspace/lib/.libs/libaudit.so ../../lib/.libs/libaudit.so ../../common/.libs/libaucommon.a -Wl,-rpath -Wl,/home/grimmauld/coding/audit-userspace/auparse/.libs -Wl,-rpath -Wl,/home/grimmauld/coding/audit-userspace/lib/.libs -Wl,-rpath -Wl,/home/grimmauld/coding/audit-userspace/outputs/lib/lib
libtool: link: gcc -g -O2 -o auparselol_test auparselol_test.o  ../../auparse/.libs/libauparse.so /home/grimmauld/coding/audit-userspace/lib/.libs/libaudit.so ../../lib/.libs/libaudit.so ../../common/.libs/libaucommon.a -Wl,-rpath -Wl,/home/grimmauld/coding/audit-userspace/auparse/.libs -Wl,-rpath -Wl,/home/grimmauld/coding/audit-userspace/lib/.libs -Wl,-rpath -Wl,/home/grimmauld/coding/audit-userspace/outputs/lib/lib
libtool: link: gcc -g -O2 -o auparse_test auparse_test.o  ../../auparse/.libs/libauparse.so /home/grimmauld/coding/audit-userspace/lib/.libs/libaudit.so ../../lib/.libs/libaudit.so ../../common/.libs/libaucommon.a -Wl,-rpath -Wl,/home/grimmauld/coding/audit-userspace/auparse/.libs -Wl,-rpath -Wl,/home/grimmauld/coding/audit-userspace/lib/.libs -Wl,-rpath -Wl,/home/grimmauld/coding/audit-userspace/outputs/lib/lib
/nix/store/z3za8hfc24wb117s50p8b10agjkgm039-binutils-2.44/bin/ld: databuf_test.o: in function `test_basic':
/home/grimmauld/coding/audit-userspace/auparse/test/databuf_test.c:14:(.text.startup+0x4d): undefined reference to `databuf_init'
/nix/store/z3za8hfc24wb117s50p8b10agjkgm039-binutils-2.44/bin/ld: /home/grimmauld/coding/audit-userspace/auparse/test/databuf_test.c:15:(.text.startup+0x6a): undefined reference to `databuf_append'
/nix/store/z3za8hfc24wb117s50p8b10agjkgm039-binutils-2.44/bin/ld: /home/grimmauld/coding/audit-userspace/auparse/test/databuf_test.c:19:(.text.startup+0xad): undefined reference to `databuf_append'
/nix/store/z3za8hfc24wb117s50p8b10agjkgm039-binutils-2.44/bin/ld: /home/grimmauld/coding/audit-userspace/auparse/test/databuf_test.c:23:(.text.startup+0x10c): undefined reference to `databuf_advance'
/nix/store/z3za8hfc24wb117s50p8b10agjkgm039-binutils-2.44/bin/ld: /home/grimmauld/coding/audit-userspace/auparse/test/databuf_test.c:27:(.text.startup+0x17a): undefined reference to `databuf_append'
/nix/store/z3za8hfc24wb117s50p8b10agjkgm039-binutils-2.44/bin/ld: /home/grimmauld/coding/audit-userspace/auparse/test/databuf_test.c:31:(.text.startup+0x1d5): undefined reference to `databuf_free'
/nix/store/z3za8hfc24wb117s50p8b10agjkgm039-binutils-2.44/bin/ld: databuf_test.o: in function `test_preserve':
/home/grimmauld/coding/audit-userspace/auparse/test/databuf_test.c:41:(.text.startup+0x20f): undefined reference to `databuf_init'
/nix/store/z3za8hfc24wb117s50p8b10agjkgm039-binutils-2.44/bin/ld: /home/grimmauld/coding/audit-userspace/auparse/test/databuf_test.c:42:(.text.startup+0x228): undefined reference to `databuf_append'
/nix/store/z3za8hfc24wb117s50p8b10agjkgm039-binutils-2.44/bin/ld: /home/grimmauld/coding/audit-userspace/auparse/test/databuf_test.c:43:(.text.startup+0x23e): undefined reference to `databuf_advance'
/nix/store/z3za8hfc24wb117s50p8b10agjkgm039-binutils-2.44/bin/ld: /home/grimmauld/coding/audit-userspace/auparse/test/databuf_test.c:44:(.text.startup+0x257): undefined reference to `databuf_append'
/nix/store/z3za8hfc24wb117s50p8b10agjkgm039-binutils-2.44/bin/ld: /home/grimmauld/coding/audit-userspace/auparse/test/databuf_test.c:47:(.text.startup+0x27e): undefined reference to `databuf_reset'
/nix/store/z3za8hfc24wb117s50p8b10agjkgm039-binutils-2.44/bin/ld: /home/grimmauld/coding/audit-userspace/auparse/test/databuf_test.c:51:(.text.startup+0x2e4): undefined reference to `databuf_replace'
/nix/store/z3za8hfc24wb117s50p8b10agjkgm039-binutils-2.44/bin/ld: /home/grimmauld/coding/audit-userspace/auparse/test/databuf_test.c:52:(.text.startup+0x2fa): undefined reference to `databuf_advance'
/nix/store/z3za8hfc24wb117s50p8b10agjkgm039-binutils-2.44/bin/ld: /home/grimmauld/coding/audit-userspace/auparse/test/databuf_test.c:53:(.text.startup+0x313): undefined reference to `databuf_append'
/nix/store/z3za8hfc24wb117s50p8b10agjkgm039-binutils-2.44/bin/ld: /home/grimmauld/coding/audit-userspace/auparse/test/databuf_test.c:56:(.text.startup+0x33a): undefined reference to `databuf_reset'
/nix/store/z3za8hfc24wb117s50p8b10agjkgm039-binutils-2.44/bin/ld: /home/grimmauld/coding/audit-userspace/auparse/test/databuf_test.c:60:(.text.startup+0x378): undefined reference to `databuf_free'
/nix/store/z3za8hfc24wb117s50p8b10agjkgm039-binutils-2.44/bin/ld: databuf_test: hidden symbol `databuf_init' isn't defined
/nix/store/z3za8hfc24wb117s50p8b10agjkgm039-binutils-2.44/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:678: databuf_test] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/home/grimmauld/coding/audit-userspace/auparse/test'
make[3]: *** [Makefile:2269: all-recursive] Error 1
make[3]: Leaving directory '/home/grimmauld/coding/audit-userspace/auparse'
make[2]: *** [Makefile:1089: all] Error 2
make[2]: Leaving directory '/home/grimmauld/coding/audit-userspace/auparse'
make[1]: *** [Makefile:467: all-recursive] Error 1
make[1]: Leaving directory '/home/grimmauld/coding/audit-userspace'
make: *** [Makefile:399: all] Error 2
```

The error log here suggests some symbols can't be resolved, hinting at a bad include path for libraries.

Bisecting this issue points to commit https://github.com/linux-audit/audit-userspace/commit/f0f64125bea6484ffd60c3d44b3034f3612f8171:
```
f0f64125bea6484ffd60c3d44b3034f3612f8171 is the first bad commit
commit f0f64125bea6484ffd60c3d44b3034f3612f8171 (HEAD)
Author: Steve Grubb <ausearch.1@gmail.com>
Date:   Thu Jun 19 16:50:14 2025 -0400

    Reorganize the auparse tests

    auparse: integrate tests with automake

    Run the auparse tests directly through Automake’s TESTS list.
    Wrapper scripts (run_auparse_test.sh and run_auparselol_test.sh)
    handle log copying and comparisons so each test shows up in the testsuite
    summary.  The old check-local logic is removed and configure.ac transforms
    the run-*.sh scripts.

 auparse/Makefile.am                    |  2 +-
 auparse/test/Makefile.am               | 32 +++++++++-----------------------
 auparse/test/run_auparse_tests.sh.in   | 24 ++++++++++++++++++++++++
 auparse/test/run_auparselol_test.sh.in | 10 ++++++++++
 configure.ac                           | 20 +++++++++++++++++++-
 5 files changed, 63 insertions(+), 25 deletions(-)
 create mode 100755 auparse/test/run_auparse_tests.sh.in
 create mode 100755 auparse/test/run_auparselol_test.sh.in
```

The issue can be bypassed by just not building `databuf_test`. It is not being run anyways. That said, this isn't ideal:
```diff
diff --git a/auparse/test/Makefile.am b/auparse/test/Makefile.am
index 89c92447..3d221004 100644
--- a/auparse/test/Makefile.am
+++ b/auparse/test/Makefile.am
@@ -21,8 +21,8 @@
 #
 
 CONFIG_CLEAN_FILES = *.loT *.rej *.orig *.cur
-noinst_PROGRAMS = auparse_test auparselol_test lookup_test databuf_test
-TESTS = run_auparse_tests.sh run_auparselol_test.sh lookup_test databuf_test
+noinst_PROGRAMS = auparse_test auparselol_test lookup_test
+TESTS = run_auparse_tests.sh run_auparselol_test.sh lookup_test
 dist_check_SCRIPTS = run_auparse_tests.sh run_auparselol_test.sh
 if USE_PYTHON3
 TESTS += auparse_test.py
```

It is well possible i am doing something stupid, but seeing as this happens both in the nix build sandbox and in a regular `make`-based build, i don't think i caused this issue.

**Comment by LordGrimmauld** [comment]
What might be happening is: I am running in a "clean" environment. If it is pulling libraries from e.g. global `/lib` directory on "normal" distros, then this break of missing the explicit link might not happen.

**Comment by LordGrimmauld** [comment]
There is also a whole bunch of errors when building against musl, but i'll poke at that myself for a bit and open a second issue for that.

**Comment by stevegrubb** [comment]
This has more to do with symbol visibility. Those are hidden symbols, but like Attila said, CI tests would have caught this. @LordGrimmauld What compiler & version are you using?

**Comment by LordGrimmauld** [comment]
Full version numbers, fwiw:
- NixOS (current unstable)
- GNU Make 4.4.1
- autoreconf (GNU Autoconf) 2.72
- gcc (GCC) 14.3.0
- libtool (GNU libtool) 2.5.4
- GNU ld (GNU Binutils) 2.44
- building against glibc 2.40-66 (musl is broken in different ways)

**Comment by LordGrimmauld** [comment]
Ah fair enough! On nix we disable static for all builds by default, that'd do it.

**Comment by LordGrimmauld** [comment]
Feel free to reopen if you want to actively support builds with static disabled, but i don't want to coerce you into extra work/supported targets, that'd not be fair
